



ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_attempts DISABLE ROW LEVEL SECURITY;
ALTER TABLE quizzes DISABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE learning_materials DISABLE ROW LEVEL SECURITY;
ALTER TABLE material_categories DISABLE ROW LEVEL SECURITY;


SELECT COUNT(*) as total_attempts FROM quiz_attempts;
SELECT COUNT(*) as total_quizzes FROM quizzes;
SELECT COUNT(*) as total_profiles FROM profiles;



